version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/express-app
  permissions:
    - object: /home/ubuntu/express-app
      owner: ubuntu
      group: ubuntu
      type:
        - directory
        - file
hooks:
#  ApplicationStop:
#    - location: scripts/application_stop.sh
#      timeout: 300
#      runas: ubuntu

  BeforeInstall:
    - location: /scripts/before_install.sh
      timeout: 300
      runas: ubuntu
#
#  ApplicationStart:
#    - location: /home/ubuntu/express-app/scripts/application_start.sh
#      timeout: 300
#      runas: ubuntu

